#!/bin/sh

# Get the latest package lists
apt update

# Install Nala
apt install nala

# Install
nala install steam -y
nala install discord -y
nala install lutris -y
nala install protonup -y
nala install input remapper -y
nala install solaar -y


# Final message
echo Donezo, quitting.

# Exit the script
exit 0
