#!/bin/sh

# Add pacstall
sudo bash -c "$(curl -fsSL https://pacstall.dev/q/install)"

# Get the latest package lists
apt update

# Install Nala from pacstall
pacstall -I nala-deb

# Install from Repo
nala install steam -y
nala install discord -y
nala install lutris -y
nala install protonup -y
nala install input remapper -y
nala install solaar -y


# Final message
echo Donezo, quitting.

# Exit the script
exit 0
